### ISSUE TITLE
CSS Positioning of the button isn't inline with the results and examples boxes.

### ISSUE THREAD

**Issue by jordanrobinson** [JordanRobinson/when-will-cron-fire#1]

**Comment by furzeface** [comment]
Float left? What do you think @ablackledge?

**Comment by jordanrobinson** [comment]
Naturally the first thing I tried

**Comment by jordanrobinson** [comment]
Nicely done! :thumbsup: Let me know how you figured it out at work tomorrow.

**Comment by furzeface** [comment]
I've already forgotten, sorry! 

---
- http://furzeface.com/blog
- @furzeface
